name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

env:
  ECR_REGISTRY: 273030403034.dkr.ecr.us-west-2.amazonaws.com
  ECR_REPOSITORY: py_api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            273030403034.dkr.ecr.us-west-2.amazonaws.com/py_api:latest

 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::273030403034:role/githubrunner
          aws-region: us-west-2
 
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push 273030403034.dkr.ecr.us-west-2.amazonaws.com/py_api:latest
  
